version: '3.8'

services:
  laravel-app:
    build: .
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: labormanual
      DB_USERNAME: postgres
      DB_PASSWORD: root
    depends_on:
      - postgres
    networks:
      - laravel_network
    command: >
      sh -c "if [ ! -f .env ]; then cp .env.example .env; fi &&
            chmod 644 .env &&
            chown www-data:www-data .env &&
            php artisan key:generate &&
            php artisan config:cache &&
            php artisan migrate:refresh --force &&
            php artisan db:seed --force &&
            php artisan serve --host=0.0.0.0 --port=8000"

  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: labormanual
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  postgres_data:
