version: '3.8'

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      APP_ENV: production
      APP_DEBUG: false
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: labormanual
      DB_USERNAME: postgres
      DB_PASSWORD: root
    depends_on:
      - postgres
    networks:
      - laravel_network
    command: >
      sh -c "if [ ! -f .env ]; then cp .env.example .env; fi &&
            php artisan key:generate &&
            php artisan config:cache &&
            for i in {1..10}; do
              php artisan migrate --force && break || echo 'Waiting for database...' && sleep 5;
            done &&
            php artisan db:seed --force &&
            echo 'Laravel setup completed successfully!' && php-fpm "

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80" # Exposing Nginx on port 80 for external traffic
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - laravel-app
    networks:
      - laravel_network

  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: labormanual
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432" # Exposing PostgreSQL for external tools (optional)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  laravel_network:
    driver: bridge

volumes:
  postgres_data:
