name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Laravel app image
      run: |
        # Build the Laravel app Docker image
        docker build -t kingdinner1/laravel-app:latest -f Dockerfile .
        
        # Push the Laravel app image to Docker Hub
        docker push kingdinner1/laravel-app:latest

    - name: Build and push PostgreSQL image (optional)
      run: |
        # Build the PostgreSQL Docker image
        docker build -t kingdinner1/postgres:latest -f postgres.Dockerfile .
        
        # Push the PostgreSQL image to Docker Hub
        docker push kingdinner1/postgres:latest
